[package]
name = "tang-ad"
version = "0.1.1"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "Reverse-mode automatic differentiation"
repository.workspace = true
readme = "README.md"
keywords = ["autodiff", "gradient", "backprop", "math"]
categories = ["mathematics", "science"]
include = ["src/**/*", "README.md"]

[dependencies]
tang = { workspace = true }
tang-la = { workspace = true }

[dev-dependencies]
approx = "0.5"
